<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Departement;
use App\Models\Ville;
use App\Models\Arrondissement;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    protected $chunk = 1000;
    public function run(): void
    {
        // User::factory(10)->create();

        User::factory()->create([
            'name' => 'Test User',
            'email' => 'test@example.com',
            'arrondissement'=>12,
            'statut'=>1,
            'grade'=>"instituteur",
            'phone_number'=>90000001,
        ]);
         Departement::insert([
            ['id' => 1, 'name' => 'Alibori'],
            ['id' => 2, 'name' => 'Atacora'],
            ['id' => 3, 'name' => 'Atlantique'],
            ['id' => 4, 'name' => 'Borgou'],
            ['id' => 5, 'name' => 'Collines'],
            ['id' => 6, 'name' => 'Couffo'],
            ['id' => 7, 'name' => 'Donga'],
            ['id' => 8, 'name' => 'Littoral'],
            ['id' => 9, 'name' => 'Mono'],
            ['id' => 10, 'name' => 'Ouémé'],
            ['id' => 11, 'name' => 'Plateau'],
            ['id' => 12, 'name' => 'Zou'],
        ]);
        Ville::insert([
            //departement de l'alibori
            ['name'=> 'Banikoara','departement_id'=>1],
            ['name'=> 'Gogounou','departement_id'=>1],
            ['name'=> 'Kandi','departement_id'=>1],
            ['name'=> 'Karimama','departement_id'=>1],
            ['name'=> 'Malanville','departement_id'=>1],
            ['name'=> 'Segbana','departement_id'=>1],
            // departement de l'atacora
            ['name'=> 'Boukoumbé','departement_id'=>2],
            ['name'=> 'Cobly','departement_id'=>2],
            ['name'=> 'Kérou','departement_id'=>2],
            ['name'=> 'Kouandé','departement_id'=>2],
            ['name'=> 'Matéri','departement_id'=>2],
            ['name'=> 'Natitingou','departement_id'=>2],
            ['name'=> 'Péhunco','departement_id'=>2],
            ['name'=> 'Tanguiéta','departement_id'=>2],
            ['name'=> 'Toucountouna','departement_id'=>2],
            //Atlantique
            ['name'=> 'Abomey-Calavi','departement_id'=>3],
            ['name'=> 'Allada','departement_id'=>3],
            ['name'=> 'Kpomassè','departement_id'=>3],
            ['name'=> 'Ouidah','departement_id'=>3],
            ['name'=> 'Sô-Ava','departement_id'=>3],
            ['name'=> 'Toffo','departement_id'=>3],
            ['name'=> 'Tori-Bossito','departement_id'=>3],
            ['name'=> 'Zè','departement_id'=>3],
            //Borgou
            ['name'=> 'Bembéréké','departement_id'=>4],
            ['name'=> 'Kalalé','departement_id'=>4],
            ['name'=> 'N\'Dali','departement_id'=>4],
            ['name'=> 'Nikki','departement_id'=>4],
            ['name'=> 'Parakou','departement_id'=>4],
            ['name'=> 'Pèrèrè','departement_id'=>4],
            ['name'=> 'Sinendé','departement_id'=>4],
            ['name'=> 'Tchaourou','departement_id'=>4],
            //Collines
            ['name'=> 'Bantè','departement_id'=>5],
            ['name'=> 'Dassa-Zoumè','departement_id'=>5],
            ['name'=> 'Glazoué','departement_id'=>5],
            ['name'=> 'Ouèssè','departement_id'=>5],
            ['name'=> 'Savalou','departement_id'=>5],
            ['name'=> 'Savè','departement_id'=>5],
            //Couffo
            ['name'=> 'Aplahoué','departement_id'=>6],
            ['name'=> 'Djakotomey','departement_id'=>6],
            ['name'=> 'Dogbo-Tota','departement_id'=>6],
            ['name'=> 'Klouékanmè','departement_id'=>6],
            ['name'=> 'Lalo','departement_id'=>6],
            ['name'=> 'Toviklin','departement_id'=>6],
            //Donga
            ['name'=> 'Bassila','departement_id'=>7],
            ['name'=> 'Copargo','departement_id'=>7],
            ['name'=> 'Djougou','departement_id'=>7],
            ['name'=> 'Ouaké','departement_id'=>7],
            //littoral
            ['name'=> 'Cotonou','departement_id'=>8],
            //Mono
            ['name'=> 'Athiémé','departement_id'=>9],
            ['name'=> 'Bopa','departement_id'=>9],
            ['name'=> 'Comè','departement_id'=>9],
            ['name'=> 'Grand-Popo','departement_id'=>9],
            ['name'=> 'Houéyogbé','departement_id'=>9],
            ['name'=> 'Lokossa','departement_id'=>9],
            //Ouémé
            ['name'=> 'Adjarra','departement_id'=>10],
            ['name'=> 'Adjohoun','departement_id'=>10],
            ['name'=> 'Aguégués','departement_id'=>10],
            ['name'=> 'Akpro-Missérété','departement_id'=>10],
            ['name'=> 'Avrankou','departement_id'=>10],
            ['name'=> 'Bonou','departement_id'=>10],
            ['name'=> 'Dangbo','departement_id'=>10],
            ['name'=> 'Porto-Novo','departement_id'=>10],
            ['name'=> 'Sèmè-Kpodji','departement_id'=>10],
            //Plateau
            ['name'=> 'Adja-Ouèrè','departement_id'=>11],
            ['name'=> 'Ifangni','departement_id'=>11],
            ['name'=> 'Kétou','departement_id'=>11],
            ['name'=> 'Pobè','departement_id'=>11],
            ['name'=> 'Sakété','departement_id'=>11],
            //Zou
            ['name'=> 'Abomey','departement_id'=>12],
            ['name'=> 'Agbangnizoun','departement_id'=>12],
            ['name'=> 'Bohicon','departement_id'=>12],
            ['name'=> 'Covè','departement_id'=>12],
            ['name'=> 'Djidja','departement_id'=>12],
            ['name'=> 'Zagnanado','departement_id'=>12],
            ['name'=> 'Ouinhi','departement_id'=>12],
            ['name'=> 'Zogbodomey','departement_id'=>12],
            ['name'=> 'Za-Kpota','departement_id'=> 12],

        ]);
        Arrondissement::insert([
            //banikoara
            ["name"=>"Banikoara","ville_id"=>1],
            ["name"=>"Founougo","ville_id"=>1],
            ["name"=>"Gomparou", "ville_id"=>1],
            ["name"=>"Goumori","ville_id"=>1],
            ["name"=>"Kokey","ville_id"=>1],
            ["name"=>"Kokiborou","ville_id"=>1],
            ["name"=>"Ounet","ville_id"=>1],
            ["name"=>"Sompérékou","ville_id"=>1],
            ["name"=>"Soroko","ville_id"=>1],
            ["name"=>"Toura","ville_id"=>1],
            //Gogounou
            ["name"=>"Bagou","ville_id"=>2],
            ["name"=>"Gogounou","ville_id"=>2],
            ["name"=>"Gounarou","ville_id"=>2],
            ["name"=>"Ouara","ville_id"=>2],
            ["name"=>"Sori","ville_id"=>2],
            ["name"=>"Zoungou-Pantrossi","ville_id"=>2],
            //Kandi
            ["name"=>"Angaradébou", "ville_id"=>3],
            ["name"=>"Bensékou","ville_id"=>3],
            ["name"=>"Donwari","ville_id"=>3],
            ["name"=>"Kandi I","ville_id"=>3],
            ["name"=>"Kandi II","ville_id"=>3],
            ["name"=>"Kandi III","ville_id"=>3],
            ["name"=>"Kassakou","ville_id"=>3],
            ["name"=>"Saah","ville_id"=>3],
            ["name"=>"Sam","ville_id"=> 3],
            ["name"=>"Sonsoro","ville_id"=>3],
            //Karimama
            ["name"=>"Birni Lafia","ville_id"=>4],
            ["name"=>"Bogo-Bogo","ville_id"=>4],
            ["name"=>"Karimama-centre","ville_id"=>4],
            ["name"=>"Kompa","ville_id"=>4],
            ["name"=>"Monsey","ville_id"=> 4],
            //Malanville
            ["name"=>"Garou","ville_id"=>5],
            ["name"=>"Guéné","ville_id"=>5],
            ["name"=>"Malanville","ville_id"=>5],
            ["name"=>"Madécali","ville_id"=>5],
            ["name"=>"Toumboutou","ville_id"=>5],
            //Segbana
            ["name"=>"Libantè","ville_id"=>6],
            ["name"=>"Liboussou","ville_id"=>6],
            ["name"=>"Lougou","ville_id"=>6],
            ["name"=>"Segbana","ville_id"=>6],
            ["name"=>"Sokotindji","ville_id"=> 6],
            //Boukoumbé
            ["name"=>"Boukoumbé","ville_id"=>7],
            ["name"=>"Dipoli","ville_id"=>7],
            ["name"=>"Korontière","ville_id"=>7],
            ["name"=>"Kossoucoingou","ville_id"=>7],
            ["name"=>"Manta","ville_id"=>7],
            ["name"=>"Natta","ville_id"=>7],
            ["name"=>"Tabota","ville_id"=>7],
            //Cobly
            ["name"=>"Cobly","ville_id"=>8],
            ["name"=>"Datori","ville_id"=>8],
            ["name"=>"Kountori","ville_id"=>8],
            ["name"=>"Tapoga","ville_id"=>8],
            //Kérou
            ["name"=>"Brignamaro","ville_id"=>9],
            ["name"=>"Firou","ville_id"=>9],
            ["name"=>"Kérou","ville_id"=>9],
            ["name"=>"Koabagou","ville_id"=>9],
            //Kouandé
            ["name"=>"Birni","ville_id"=>10],
            ["name"=>"Chabi-Couma","ville_id"=>10],
            ["name"=>"Fô-Tancé","ville_id"=>10],
            ["name"=>"Guilmaro","ville_id"=>10],
            ["name"=>"Kouandé","ville_id"=>10],
            ["name"=>"Oroukayo","ville_id"=>10],
            //Matéri
            ["name"=>"Dassari","ville_id"=>11],
            ["name"=>"Gouandé","ville_id"=>11],
            ["name"=>"Matéri","ville_id"=>11],
            ["name"=>"Nodi","ville_id"=>11],
            ["name"=>"Tantéga","ville_id"=>11],
            ["name"=>"Tchianhoun-Cossi","ville_id"=>11],
            //Natitingou
            ["name"=>"Kotopounga","ville_id"=>12],
            ["name"=>"Kouaba","ville_id"=>12],
            ["name"=>"Koundata","ville_id"=>12],
            ["name"=>"Natitingou I","ville_id"=>12],
            ["name"=>"Natitingou II","ville_id"=>12],
            ["name"=>"Natitingou III","ville_id"=>12],
            ["name"=>"Natitingou IV","ville_id"=>12],
            ["name"=>"Perma","ville_id"=>12],
            ["name"=>"Tchoumi-Tchoumi","ville_id"=>12],
            //Péhunco
            ["name"=>"Gnémasson","ville_id"=>13],
            ["name"=>"Péhunco","ville_id"=>13],
            ["name"=>"Tobré","ville_id"=>13],
            //Tanguiéta
            ["name"=>"Cotiakou","ville_id"=>14],
            ["name"=>"N'Dahonta","ville_id"=>14],
            ["name"=>"Taiakou","ville_id"=>14],
            ["name"=>"Tanguiéta","ville_id"=>14],
            ["name"=>"Tanongou","ville_id"=>14],
            //Toucountouna
            ["name"=>"Kouarfa","ville_id"=>15],
            ["name"=>"Tampégré","ville_id"=>15],
            ["name"=>"Toucountouna","ville_id"=>15],
            //Abomey-Calavi
            ["name"=>"Abomey-Calavi","ville_id"=>16],
            ["name"=>"Akassato","ville_id"=>16],
            ["name"=>"Godomey","ville_id"=>16],
            ["name"=>"Glo-Djigbé","ville_id"=>16],
            ["name"=>"Hêvié","ville_id"=>16],
            ["name"=>"Kpanroun","ville_id"=>16],
            ["name"=>"Ouèdo","ville_id"=>16],
            ["name"=>"Togba","ville_id"=>16],
            ["name"=>"Zinvié","ville_id"=>16],
            //Allada
            ["name"=>"Agbanou", "ville_id"=>17],
            ["name"=>"Ahouannonzoun", "ville_id"=>17],
            ["name"=>"Allada", "ville_id"=>17],
            ["name"=>"Attogon", "ville_id"=>17],
            ["name"=>"Avakpa", "ville_id"=>17],
            ["name"=>"Ayou", "ville_id"=>17],
            ["name"=>"Hinvi", "ville_id"=>17],
            ["name"=>"Lissègazoun", "ville_id"=>17],
            ["name"=>"Lon-Agonmey", "ville_id"=>17],
            ["name"=>"Sekou", "ville_id"=>17],
            ["name"=>"Togoudo", "ville_id"=>17],
            ["name"=>"Tokpa-Avagoudo", "ville_id"=>17],
            //Kpomassè
            ["name"=>"Aganmalomè","ville_id"=>18],
            ["name"=>"Agbanto","ville_id"=>18],
            ["name"=>"Agonkanmè","ville_id"=>18],
            ["name"=>"Dédomè","ville_id"=>18],
            ["name"=>"Dékanmè","ville_id"=>18],
            ["name"=>"Kpomassè","ville_id"=>18],
            ["name"=>"Sègbèya","ville_id"=>18],
            ["name"=>"Sègbohouè","ville_id"=>18],
            ["name"=>"Tokpa-Domè","ville_id"=>18],
            //Ouidah
            ["name"=>"Avlékété","ville_id"=>19],
            ["name"=>"Djègbadji","ville_id"=>19],
            ["name"=>"Gakpé","ville_id"=>19],
            ["name"=>"Houakpè-Daho","ville_id"=>19],
            ["name"=>"Ouidah I","ville_id"=>19],
            ["name"=>"Ouidah II","ville_id"=>19],
            ["name"=>"Ouidah III","ville_id"=>19],
            ["name"=>"Ouidah IV","ville_id"=>19],
            ["name"=>"Pahou","ville_id"=>19],
            ["name"=>"Savi","ville_id"=>19],
            //Sô-Ava
            ["name"=>"Ahomey-Lokpo", "ville_id"=>20],
            ["name"=>"Dékanmey", "ville_id"=>20],
            ["name"=>"Ganvié I", "ville_id"=>20],
            ["name"=>"Ganvié II", "ville_id"=>20],
            ["name"=>"Houédo-Aguékon", "ville_id"=>20],
            ["name"=>"Sô-Ava", "ville_id"=>20],
            ["name"=>"Vekky","ville_id"=>20],
            //Toffo
            ["name"=>"Agué","ville_id"=>21],
            ["name"=>"Colli-Agbamè","ville_id"=>21],
            ["name"=>"Coussi","ville_id"=>21],
            ["name"=>"Damè","ville_id"=>21],
            ["name"=>"Djanglanmè","ville_id"=>21],
            ["name"=>"Houègbo","ville_id"=>21],
            ["name"=>"Kpomè","ville_id"=>21],
            ["name"=>"Sè","ville_id"=>21],
            ["name"=>"Sèhouè","ville_id"=>21],
            ["name"=>"Toffo-Agué","ville_id"=>21],
            //Tori-Bossito
            ["name"=>"Avamè","ville_id"=>22],
            ["name"=>"Azohouè-Aliho","ville_id"=>22],
            ["name"=>"Azohouè-Cada","ville_id"=>22],
            ["name"=>"Tori-Bossito","ville_id"=>22],
            ["name"=>"Tori-Cada","ville_id"=>22],
            ["name"=>"Tori-Gare","ville_id"=>22],
            ["name"=>"Tori aïdohoue","ville_id"=>22],
            ["name"=>"Tori acadjamè","ville_id"=>22],
            //Zè
            ["name"=>"Adjan","ville_id"=>23],
            ["name"=>"Dawè","ville_id"=>23],
            ["name"=>"Djigbé","ville_id"=>23],
            ["name"=>"Dodji-Bata","ville_id"=>23],
            ["name"=>"Hèkanmé","ville_id"=>23],
            ["name"=>"Koundokpoé","ville_id"=>23],
            ["name"=>"Sèdjè-Dénou","ville_id"=>23],
            ["name"=>"Sèdjè-Houégoudo","ville_id"=>23],
            ["name"=>"Tangbo-Djevié","ville_id"=>23],
            ["name"=>"Yokpo","ville_id"=>23],
            ["name"=>"Zè","ville_id"=>23],
            //Bembéréké
            ["name"=>"Bembéréké","ville_id"=>24],
            ["name"=>"Béroubouay","ville_id"=>24],
            ["name"=>"Bouanri","ville_id"=>24],
            ["name"=>"Gamia","ville_id"=>24],
            ["name"=>"Ina","ville_id"=>24],
            //Kalalé
            ["name"=>"Basso","ville_id"=>25],
            ["name"=>"Bouka","ville_id"=>25],
            ["name"=>"Dérassi","ville_id"=>25],
            ["name"=>"Dunkassa","ville_id"=>25],
            ["name"=>"Kalalé","ville_id"=>25],
            ["name"=>"Péonga","ville_id"=>25],
            //N'Dali
            ["name"=>"Bori","ville_id"=>26],
            ["name"=>"Gbégourou","ville_id"=>26],
            ["name"=>"N'Dali","ville_id"=>26],
            ["name"=>"Ouénou","ville_id"=>26],
            ["name"=>"Sirarou","ville_id"=>26],
            //Nikki
            ["name"=>"Biro","ville_id"=>27],
            ["name"=>"Gnonkourakali","ville_id"=>27],
            ["name"=>"Nikki","ville_id"=>27],
            ["name"=>"Ouénou","ville_id"=>27],
            ["name"=>"Sérékalé","ville_id"=>27],
            ["name"=>"Suya","ville_id"=>27],
            ["name"=>"Tasso","ville_id"=>27],
            //Parakou
            ["name"=>"1er arrondissement","ville_id"=>28],
            ["name"=>"2e arrondissement","ville_id"=>28],
            ["name"=>"3e arrondissement","ville_id"=>28],
            //Pèrèrè
            ["name"=>"Gninsy","ville_id"=>29],
            ["name"=>"Guinagourou","ville_id"=>29],
            ["name"=>"Kpané","ville_id"=>29],
            ["name"=>"Pébié","ville_id"=>29],
            ["name"=>"Pèrèrè","ville_id"=>29],
            ["name"=>"Sontou","ville_id"=>29],
            //Sinendé
            ["name"=>"Fô-Bourè","ville_id"=>30],
            ["name"=>"Sèkèrè","ville_id"=>30],
            ["name"=>"Sikki","ville_id"=>30],
            ["name"=>"Sinendé","ville_id"=>30],
            //Tchaourou
            ["name"=>"Alafiarou","ville_id"=>31],
            ["name"=>"Bétérou","ville_id"=>31],
            ["name"=>"Goro","ville_id"=>31],
            ["name"=>"Kika","ville_id"=>31],
            ["name"=>"Sanson","ville_id"=>31],
            ["name"=>"Tchaourou","ville_id"=>31],
            ["name"=>"Tchatchou","ville_id"=>31],
            //Bantè
            ["name"=>"Agoua","ville_id"=>32],
            ["name"=>"Akpassi","ville_id"=>32],
            ["name"=>"Atokoligbé","ville_id"=>32],
            ["name"=>"Bantè","ville_id"=>32],
            ["name"=>"Bobè","ville_id"=>32],
            ["name"=>"Gouka","ville_id"=>32],
            ["name"=>"Koko","ville_id"=>32],
            ["name"=>"Lougba","ville_id"=>32],
            ["name"=>"Pira","ville_id"=>32],
            //Dassa-Zoumè
            ["name"=>"Akofodjoulè","ville_id"=>33],
            ["name"=>"Dassa I","ville_id"=>33],
            ["name"=>"Dassa II","ville_id"=>33],
            ["name"=>"Gbaffo","ville_id"=>33],
            ["name"=>"Kerè","ville_id"=>33],
            ["name"=>"Kpingni","ville_id"=>33],
            ["name"=>"Lèma","ville_id"=>33],
            ["name"=>"Paouignan","ville_id"=>33],
            ["name"=>"Soclogbo","ville_id"=>33],
            ["name"=>"Tré","ville_id"=>33],
            //Glazoué
            ["name"=>"Aklankpa","ville_id"=>34],
            ["name"=>"Assanté","ville_id"=>34],
            ["name"=>"Glazoué","ville_id"=>34],
            ["name"=>"Gomè","ville_id"=>34],
            ["name"=>"Kpakpaza","ville_id"=>34],
            ["name"=>"Magoumi","ville_id"=>34],
            ["name"=>"Ouedèmè","ville_id"=>34],
            ["name"=>"Sokponta","ville_id"=>34],
            ["name"=>"Thio","ville_id"=>34],
            ["name"=>"Zaffé","ville_id"=>34],
            //Ouèssè
            ["name"=>"Challa-Ogoi","ville_id"=>35],
            ["name"=>"Djègbè","ville_id"=>35],
            ["name"=>"Gbanlin","ville_id"=>35],
            ["name"=>"Kémon","ville_id"=>35],
            ["name"=>"Kilibo","ville_id"=>35],
            ["name"=>"Laminou","ville_id"=>35],
            ["name"=>"Odougba","ville_id"=>35],
            ["name"=>"Ouèssè","ville_id"=>35],
            ["name"=>"Toui","ville_id"=>35],
            //Savalou
            ["name"=>"Djaloukou","ville_id"=>36],
            ["name"=>"Doumè","ville_id"=>36],
            ["name"=>"Gobada","ville_id"=>36],
            ["name"=>"Kpataba","ville_id"=>36],
            ["name"=>"Lahotan","ville_id"=>36],
            ["name"=>"Lèma","ville_id"=>36],
            ["name"=>"Logozohè","ville_id"=>36],
            ["name"=>"Monkpa","ville_id"=>36],
            ["name"=>"Ottola","ville_id"=>36],
            ["name"=>"Ouèssè","ville_id"=>36],
            ["name"=>"Savalou-aga","ville_id"=>36],
            ["name"=>"Savalou-agbado","ville_id"=>36],
            ["name"=>"Savalou-attakè","ville_id"=>36],
            ["name"=>"Tchetti","ville_id"=>36],
            //Savè
            ["name"=>"Adido","ville_id"=>37],
            ["name"=>"Bèssè","ville_id"=>37],
            ["name"=>"Boni","ville_id"=>37],
            ["name"=>"Kaboua","ville_id"=>37],
            ["name"=>"Ofè","ville_id"=>37],
            ["name"=>"Okpara","ville_id"=>37],
            ["name"=>"Plateau","ville_id"=>37],
            ["name"=>"Sakin","ville_id"=>37],
            //Aplahoué
            ["name"=>"Aplahoué","ville_id"=>38],
            ["name"=>"Atomè","ville_id"=>38],
            ["name"=>"Azovè","ville_id"=>38],
            ["name"=>"Dekpo","ville_id"=>38],
            ["name"=>"Godohou","ville_id"=>38],
            ["name"=>"Kissamey","ville_id"=>38],
            ["name"=>"Lonkly","ville_id"=>38],
            //Djakotomey
            ["name"=>"Adjintimey","ville_id"=>39],
            ["name"=>"Bètoumey","ville_id"=>39],
            ["name"=>"Djakotomey I","ville_id"=>39],
            ["name"=>"Djakotomey II","ville_id"=>39],
            ["name"=>"Gohomey","ville_id"=>39],
            ["name"=>"Houègamey","ville_id"=>39],
            ["name"=>"Kinkinhoué","ville_id"=>39],
            ["name"=>"Kokohoué","ville_id"=>39],
            ["name"=>"Kpoba","ville_id"=>39],
            ["name"=>"Sokouhoué","ville_id"=>39],
            //Dogbo-Tota
            ["name"=>"Ayomi","ville_id"=>40],
            ["name"=>"Dèvè","ville_id"=>40],
            ["name"=>"Honton","ville_id"=>40],
            ["name"=>"Lokogohoué","ville_id"=>40],
            ["name"=>"Madjrè","ville_id"=>40],
            ["name"=>"Tota","ville_id"=>40],
            ["name"=>"Totchagni","ville_id"=>40],
            //Klouékanmè
            ["name"=>"Adjanhonmè","ville_id"=>41],
            ["name"=>"Ahogbèya","ville_id"=>41],
            ["name"=>"Aya-Hohoué","ville_id"=>41],
            ["name"=>"Djotto, Hondji","ville_id"=>41],
            ["name"=>"Klouékanmè","ville_id"=>41],
            ["name"=>"Lanta","ville_id"=>41],
            ["name"=>"Tchikpé","ville_id"=>41],
            //Lalo
            ["name"=>"Adoukandji","ville_id"=>42],
            ["name"=>"Ahondjinnako","ville_id"=>42],
            ["name"=>"Ahomadégbé","ville_id"=>42],
            ["name"=>"Banigbé","ville_id"=>42],
            ["name"=>"Gnizounmè","ville_id"=>42],
            ["name"=>"Hlassamè","ville_id"=>42],
            ["name"=>"Lalo","ville_id"=>42],
            ["name"=>"Lokogba","ville_id"=>42],
            ["name"=>"Tchito","ville_id"=>42],
            ["name"=>"Tohou","ville_id"=>42],
            ["name"=>"Zalli","ville_id"=>42],
            //Toviklin
            ["name"=>"Adjido","ville_id"=>43],
            ["name"=>"Avédjin","ville_id"=>43],
            ["name"=>"Doko","ville_id"=>43],
            ["name"=>"Houédogli","ville_id"=>43],
            ["name"=>"Missinko","ville_id"=>43],
            ["name"=>"Tannou-Gola","ville_id"=>43],
            ["name"=>"Toviklin","ville_id"=>43],
            //Bassila
            ["name"=>"Alédjo", "ville_id"=>44],
            ["name"=>"Bassila", "ville_id"=>44],
            ["name"=>"Manigri","ville_id"=>44],
            ["name"=>"Pénéssoulou", "ville_id"=>44],
            //Copargo
            ["name"=>"Anandana","ville_id"=>45],
            ["name"=>"Copargo","ville_id"=>45],
            ["name"=>"Pabégou","ville_id"=>45],
            ["name"=>"Singré","ville_id"=>45],
            //Djougou
            ["name"=>"Barei","ville_id"=>46],
            ["name"=>"Bariénou","ville_id"=>46],
            ["name"=>"Bélléfoungou","ville_id"=>46],
            ["name"=>"Bougou","ville_id"=>46],
            ["name"=>"Djougou I","ville_id"=>46],
            ["name"=>"Djougou II","ville_id"=>46],
            ["name"=>"Djougou III","ville_id"=>46],
            ["name"=>"Kolokondé","ville_id"=>46],
            ["name"=>"Onklou","ville_id"=>46],
            ["name"=>"Patargo","ville_id"=>46],
            ["name"=>"Pélébina","ville_id"=>46],
            ["name"=>"Sérou","ville_id"=>46],
            //Ouaké
            ["name"=>"Badjoudè","ville_id"=>47],
            ["name"=>"Kondé","ville_id"=>47],
            ["name"=>"Ouaké","ville_id"=>47],
            ["name"=>"Sèmèrè I","ville_id"=>47],
            ["name"=>"Sèmèrè II","ville_id"=>47],
            ["name"=>"Tchalinga","ville_id"=>47],
            //Cotonou
            ["name"=>"1er arrondissement","ville_id"=>48],
            ["name"=>"2e arrondissement","ville_id"=>48],
            ["name"=>"3e arrondissement","ville_id"=>48],
            ["name"=>"4e arrondissement","ville_id"=>48],
            ["name"=>"5e arrondissement","ville_id"=>48],
            ["name"=>"6e arrondissement","ville_id"=>48],
            ["name"=>"7e arrondissement","ville_id"=>48],
            ["name"=>"8e arrondissement","ville_id"=>48],
            ["name"=>"9e arrondissement","ville_id"=>48],
            ["name"=>"10e arrondissement","ville_id"=>48],
            ["name"=>"11e arrondissement","ville_id"=>48],
            ["name"=>"12e arrondissement","ville_id"=>48],
            ["name"=>"13e arrondissement","ville_id"=>48],
            //Athiémé
            ["name"=>"Adohoun","ville_id"=>49],
            ["name"=>"Atchannou","ville_id"=>49],
            ["name"=>"Athiémé","ville_id"=>49],
            ["name"=>"Dédékpoé","ville_id"=>49],
            ["name"=>"Kpinnou","ville_id"=>49],
            //Bopa
            ["name"=>"Agbodji","ville_id"=>50],
            ["name"=>"Badazoui","ville_id"=>50],
            ["name"=>"Bopa","ville_id"=>50],
            ["name"=>"Gbakpodji","ville_id"=>50],
            ["name"=>"Lobogo","ville_id"=>50],
            ["name"=>"Possotomè","ville_id"=>50],
            ["name"=>"Yégodoé","ville_id"=>50],
            //Comè
            ["name"=>"Agatogbo","ville_id"=>51],
            ["name"=>"Akodéha","ville_id"=>51],
            ["name"=>"Comè","ville_id"=>51],
            ["name"=>"Ouèdèmè-Pédah","ville_id"=>51],
            ["name"=>"Oumako","ville_id"=>51],
            //Grand-Popo
            ["name"=> "Adjaha","ville_id"=> 52],
            ["name"=> "Adjaha","ville_id"=> 52],
            ["name"=> "Avloh","ville_id"=> 52],
            ["name"=> "Djanglanmey","ville_id"=> 52],
            ["name"=> "Gbéhoué","ville_id"=> 52],
            ["name"=> "Grand-Popo","ville_id"=> 52],
            ["name"=> "Sazoué","ville_id"=> 52],
            //Houéyogbé
            ["name"=>"Dahé","ville_id"=>53],
            ["name"=>"Doutou","ville_id"=>53],
            ["name"=>"Honhoué","ville_id"=>53],
            ["name"=>"Houéyogbé","ville_id"=>53],
            ["name"=>"Sè","ville_id"=>53],
            ["name"=>"Zoungbonou","ville_id"=>53],
            //Lokossa
            ["name"=>"Agamé","ville_id"=>54],
            ["name"=>"Houin","ville_id"=>54],
            ["name"=>"Koudo","ville_id"=>54],
            ["name"=>"Lokossa","ville_id"=>54],
            ["name"=>"Ouèdèmè","ville_id"=>54],
            //Adjarra
            ["name"=>"Adjarra I","ville_id"=>55],
            ["name"=>"Adjarra II","ville_id"=>55],
            ["name"=>"Aglogbé","ville_id"=>55],
            ["name"=>"Honvié","ville_id"=>55],
            ["name"=>"Malanhoui","ville_id"=>55],
            ["name"=>"Médédjonou","ville_id"=>55],
            //Adjohoun
            ["name"=>"Adjohoun","ville_id"=>56],
            ["name"=>"Akpadanou","ville_id"=>56],
            ["name"=>"Awonou","ville_id"=>56],
            ["name"=>"Azowlissè","ville_id"=>56],
            ["name"=>"Dèmè","ville_id"=>56],
            ["name"=>"Gangban","ville_id"=>56],
            ["name"=>"Kodè","ville_id"=>56],
            ["name"=>"Togbota","ville_id"=>56],
            //Aguégués
            ["name"=>"Avagbodji","ville_id"=>57],
            ["name"=>"Houédomè","ville_id"=>57],
            ["name"=>"Zoungamè","ville_id"=>57],
            //Akpro-Missérété
            ["name"=>"Akpro-Missérété","ville_id"=>58],
            ["name"=>"Gomè-Sota","ville_id"=>58],
            ["name"=>"Katagon","ville_id"=>58],
            ["name"=>"Vakon","ville_id"=>58],
            ["name"=>"Zodogbomey","ville_id"=>58],
            //Avrankou
            ["name"=>"Atchoukpa","ville_id"=>59],
            ["name"=>"Avrankou","ville_id"=>59],
            ["name"=>"Djomon","ville_id"=>59],
            ["name"=>"Gbozounmè","ville_id"=>59],
            ["name"=>"Kouty","ville_id"=>59],
            ["name"=>"Ouanho","ville_id"=>59],
            ["name"=>"Sado","ville_id"=>59],
            //Bonou
            ["name"=>"Affamè","ville_id"=>60],
            ["name"=>"Atchonsa","ville_id"=>60],
            ["name"=>"Bonou","ville_id"=>60],
            ["name"=>"Damè-Wogon","ville_id"=>60],
            ["name"=>"Houinviguè","ville_id"=>60],
            //Dangbo
            ["name"=>"Dangbo","ville_id"=>61],
            ["name"=>"Dèkin","ville_id"=>61],
            ["name"=>"Gbéko","ville_id"=>61],
            ["name"=>"Houédomey","ville_id"=>61],
            ["name"=>"Hozin","ville_id"=>61],
            ["name"=>"Késsounou","ville_id"=>61],
            ["name"=>"Zounguè","ville_id"=>61],
            //Porto-Novo
            ["name"=>"1er arrondissement","ville_id"=>62],
            ["name"=>"2e arrondissement","ville_id"=>62],
            ["name"=>"3e arrondissement","ville_id"=>62],
            ["name"=>"4e arrondissement","ville_id"=>62],
            ["name"=>"5e arrondissement","ville_id"=>62],
            //Sèmè-Kpodji
            ["name"=>"Agblangandan","ville_id"=>63],
            ["name"=>"Aholouyèmè","ville_id"=>63],
            ["name"=>"Djèrègbè","ville_id"=>63],
            ["name"=>"Ekpè","ville_id"=>63],
            ["name"=>"Sèmè-Kpodji","ville_id"=>63],
            ["name"=>"Tohouè","ville_id"=>63],
            //Adja-Ouérè
            ["name"=>"Adja-Ouèrè","ville_id"=>64],
            ["name"=>"Ikpinlè","ville_id"=>64],
            ["name"=>"Kpoulou","ville_id"=>64],
            ["name"=>"Massè","ville_id"=>64],
            ["name"=>"Oko-Akarè","ville_id"=>64],
            ["name"=>"Totonnoukon","ville_id"=>64],
            //Ifangni
            ["name"=>"Banigbé","ville_id"=>65],
            ["name"=>"Daagbé","ville_id"=>65],
            ["name"=>"Tchaada","ville_id"=>65],
            ["name"=>"Ifangni","ville_id"=>65],
            ["name"=>"Ko-Koumolou","ville_id"=>65],
            ["name"=>"Lagbé","ville_id"=>65],
            //Kétou
            ["name"=>"Adakplamé","ville_id"=>66],
            ["name"=>"Idigny","ville_id"=>66],
            ["name"=>"Kpankou","ville_id"=>66],
            ["name"=>"Kétou","ville_id"=>66],
            ["name"=>"Odometa","ville_id"=>66],
            ["name"=>"Okpometa","ville_id"=>66],
            //Pobè
            ["name"=>"Ahoyéyé","ville_id"=>67],
            ["name"=>"Igana","ville_id"=>67],
            ["name"=>"Issaba","ville_id"=>67],
            ["name"=>"Pobè","ville_id"=>67],
            ["name"=>"Towé","ville_id"=>67],
            //Sakété
            ["name"=>"Aguidi","ville_id"=>68],
            ["name"=>"Ita-Djèbou]","ville_id"=>68],
            ["name"=>"Sakété I","ville_id"=>68],
            ["name"=>"Sakété II","ville_id"=>68],
            ["name"=>"Takon","ville_id"=>68],
            ["name"=>"Yoko","ville_id"=>68],
            //Abomey
            ["name"=>"Agbokpa","ville_id"=>69],
            ["name"=>"Dètohou","ville_id"=>69],
            ["name"=>"Djègbè","ville_id"=>69],
            ["name"=>"Hounli","ville_id"=>69],
            ["name"=>"Sèhoun","ville_id"=>69],
            ["name"=>"Vidolè","ville_id"=>69],
            ["name"=>"Zounzounmè","ville_id"=>69],
            //Agbangnizoun
            ["name"=>"Adahondjigon","ville_id"=>70],
            ["name"=>"Adingningon","ville_id"=>70],
            ["name"=>"Agbangnizoun","ville_id"=>70],
            ["name"=>"Kinta","ville_id"=>70],
            ["name"=>"Kpota","ville_id"=>70],
            ["name"=>"Lissazounmè","ville_id"=>70],
            ["name"=>"Sahé","ville_id"=>70],
            ["name"=>"Siwé","ville_id"=>70],
            ["name"=>"Tanvé","ville_id"=>70],
            ["name"=>"Zoungoudo","ville_id"=>70],
            //Bohicon
            ["name"=>"Agongointo","ville_id"=>71],
            ["name"=>"Avogbanna","ville_id"=>71],
            ["name"=>"Bohicon I","ville_id"=>71],
            ["name"=>"Bohicon II","ville_id"=>71],
            ["name"=>"Gnidjazoun","ville_id"=>71],
            ["name"=>"Lissèzoun","ville_id"=>71],
            ["name"=>"Ouassaho","ville_id"=>71],
            ["name"=>"Passagon","ville_id"=>71],
            ["name"=>"Saclo","ville_id"=>71],
            ["name"=>"Sodohomè","ville_id"=>71],
            //Covè
            ["name"=>"Adogbé","ville_id"=>72],
            ["name"=>"Gounli","ville_id"=>72],
            ["name"=>"Houéko","ville_id"=>72],
            ["name"=>"Houen-Hounso","ville_id"=>72],
            ["name"=>"Lainta-Cogbè","ville_id"=>72],
            ["name"=>"Naogon","ville_id"=>72],
            ["name"=>"Soli","ville_id"=>72],
            ["name"=>"Zogba","ville_id"=>72],
            //Djidja
            ["name"=>"Agondji","ville_id"=>73],
            ["name"=>"Agouna","ville_id"=>73],
            ["name"=>"Dan","ville_id"=>73],
            ["name"=>"Djidja","ville_id"=>73],
            ["name"=>"Dohouimè","ville_id"=>73],
            ["name"=>"Gobaix","ville_id"=>73],
            ["name"=>"Monsourou","ville_id"=>73],
            ["name"=>"Mougnon","ville_id"=>73],
            ["name"=>"Oungbègamè","ville_id"=>73],
            ["name"=>"Outo","ville_id"=>73],
            ["name"=>"Setto","ville_id"=>73],
            ["name"=>"Zoukon","ville_id"=>73],
            //Zagnanado
            ["name"=>"Agonli-Houégbo","ville_id"=>74],
            ["name"=>"Banamè","ville_id"=>74],
            ["name"=>"N'-Tan","ville_id"=>74],
            ["name"=>"Dovi","ville_id"=>74],
            ["name"=>"Kpédékpo","ville_id"=>74],
            ["name"=>"Zagnanado","ville_id"=>74],
            //Ouinhi
            ["name"=>"Dasso","ville_id"=>75],
            ["name"=>"Ouinhi","ville_id"=>75],
            ["name"=>"Sagon","ville_id"=>75],
            ["name"=>"Tohoué","ville_id"=>75],
            //Zogbodomey
            ["name"=>"Akiza ","ville_id"=>76],
            ["name"=>"Avlamè","ville_id"=>76],
            ["name"=>"Cana I","ville_id"=>76],
            ["name"=>"Cana II","ville_id"=>76],
            ["name"=>"Domè","ville_id"=>76],
            ["name"=>"Koussoukpa","ville_id"=>76],
            ["name"=>"Kpokissa","ville_id"=>76],
            ["name"=>"Massi","ville_id"=>76],
            ["name"=>"Tanwé-Hessou","ville_id"=>76],
            ["name"=>"Zogbodomey","ville_id"=>76],
            ["name"=>"Zoukou","ville_id"=>76],
            //Zapkota
            ["name"=>"Allahé","ville_id"=>77],
            ["name"=>"Assalin","ville_id"=>77],
            ["name"=>"Houngomey","ville_id"=>77],
            ["name"=>"Kpakpamè","ville_id"=>77],
            ["name"=>"Kpozoun","ville_id"=>77],
            ["name"=>"Za-Kpota","ville_id"=>77],
            ["name"=>"Za-Tanta","ville_id"=>77],
            ["name"=>"Zèko","ville_id"=>77],
        ]);
    }
}